global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'weather-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']